port: "8080"

db:
  username: "ayazhan"
  password: "uDpaNgwJ4CTWSIhB3GHvVB1oZVHKJnH5"
  host: "dpg-cqkgpcaju9rs738nuu80-a.frankfurt-postgres.render.com"
  port: 5432
  dbname: "project_management_db_hdvj"
  sslmode: "require"